### ISSUE TITLE
requirements

### ISSUE THREAD

**Issue by aozorahime** [GATECH-EIC/Edge-LLM#3]
Hi, can you provide the information about the requirements for running this code? since we are confused on this requirements version and got a lot of errors.

**Comment by sinuofan** [comment]
Traceback (most recent call last):
  File "/cluster/tufts/laolab/sfan06/sfanPorject/Edge-LLM/main.py", line 384, in <module>
    train()
  File "/cluster/tufts/laolab/sfan06/sfanPorject/Edge-LLM/main.py", line 194, in train
    trainer = Seq2SeqTrainer(
  File "/cluster/tufts/laolab/sfan06/sfanPorject/condaenv/edgellm/lib/python3.9/site-packages/transformers/utils/deprecation.py", line 165, in wrapped_func
    return func(*args, **kwargs)
  File "/cluster/tufts/laolab/sfan06/sfanPorject/condaenv/edgellm/lib/python3.9/site-packages/transformers/trainer_seq2seq.py", line 72, in __init__
    super().__init__(
TypeError: __init__() got an unexpected keyword argument 'processing_class'
I got kind of same question, this means the transformer version problem. I have not fix this yet.
